name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_CHANNEL: stable
  RUSTFLAGS: -D warnings # Fail on warnings

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Run tests"
    steps:
    - name: Setup | Checkout Repository
      uses: actions/checkout@v4

    - name: Setup | Rust Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Setup | Cache Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ env.RUST_CHANNEL }}

    - name: Build | Compile Project
      run: cargo build --verbose

    - name: Run | Tests
      run: cargo test --verbose

  clippy:
    runs-on: ubuntu-latest
    name: "Run clippy"
    steps:
    - name: Setup | Checkout Repository
      uses: actions/checkout@v4

    - name: Setup | Rust Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Setup | Cache Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ env.RUST_CHANNEL }}

    - name: Run | Clippy
      run: cargo clippy --verbose

  format:
    runs-on: ubuntu-latest
    name: "Run formatter"
    steps:
    - name: Setup | Checkout Repository
      uses: actions/checkout@v4

    - name: Setup | Rust Toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Setup | Cache Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ env.RUST_CHANNEL }}
    - name: Run | Formatter
      run: cargo fmt --all -- --check
